"use client";

import { formatDate } from "@/lib/utils";
import StatsPeriodControls, { type StatsViewMode } from "@/components/StatsPeriodControls";

export type CalendarValue = { value: string; hasRecord: boolean; badge?: string; isComplete?: boolean; intensity?: "none" | "low" | "medium" | "high" };
type Props = { title: string; values: Record<string, CalendarValue>; selectedYear: number; selectedMonth: number; viewMode: StatsViewMode; onViewModeChange: (mode: StatsViewMode) => void; onPeriodChange: (year: number, month: number) => void; onToday: () => void; onDayClick?: (date: string) => void };
const weekdays = ["一", "二", "三", "四", "五", "六", "日"];
function dateKey(year: number, month: number, day: number) { return `${year}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`; }
function cells(year: number, month: number) { const first = new Date(year, month - 1, 1); const days = new Date(year, month, 0).getDate(); const empty = (first.getDay() + 6) % 7; return [...Array.from({ length: empty }, () => null), ...Array.from({ length: days }, (_, i) => ({ day: i + 1, date: dateKey(year, month, i + 1) }))]; }
function valueClass(v?: CalendarValue) { if (!v?.hasRecord) return "text-slate-400"; if (v.isComplete) return "text-leaf"; return "text-emerald-600"; }
function sizeClass(v?: CalendarValue) { const l = v?.value.length ?? 0; if (l >= 7) return "text-[9px] sm:text-xs"; if (l >= 6) return "text-[10px] sm:text-sm"; return "text-[11px] sm:text-sm"; }
function cellClass(date: string, v?: CalendarValue) { const today = formatDate(new Date()); const base = "relative min-h-[58px] rounded-xl border px-1.5 py-1.5 text-left transition sm:min-h-[62px]"; const ring = date === today ? " ring-2 ring-leaf ring-offset-1" : ""; if (v?.isComplete) return `${base} border-emerald-200 bg-emerald-50${ring}`; if (v?.intensity === "high") return `${base} border-emerald-200 bg-emerald-100${ring}`; if (v?.intensity === "medium") return `${base} border-emerald-100 bg-emerald-50${ring}`; if (v?.intensity === "low") return `${base} border-line bg-mint/60${ring}`; return `${base} border-line bg-white${ring}`; }
export default function MonthlyCalendar({ title, values, selectedYear, selectedMonth, viewMode, onViewModeChange, onPeriodChange, onToday, onDayClick }: Props) { return <div className="panel"><div className="flex items-start justify-between gap-3"><h3 className="text-base font-black text-ink">{title}</h3><StatsPeriodControls viewMode={viewMode} selectedYear={selectedYear} selectedMonth={selectedMonth} onViewModeChange={onViewModeChange} onPeriodChange={onPeriodChange} onToday={onToday} /></div><div className="mt-4 grid grid-cols-7 gap-1.5 text-center text-xs font-black text-slate-400">{weekdays.map((w) => <div key={w}>{w}</div>)}</div><div className="mt-2 grid grid-cols-7 gap-1.5">{cells(selectedYear, selectedMonth).map((c, i) => c ? <button key={c.date} type="button" className={`${cellClass(c.date, values[c.date])} active:scale-[0.99]`} onClick={() => onDayClick?.(c.date)}>{values[c.date]?.badge ? <div className="absolute right-1.5 top-1 inline-flex h-4 min-w-4 items-center justify-center rounded-full bg-leaf px-0.5 text-[10px] font-black leading-none text-white sm:h-5 sm:min-w-5 sm:text-xs">{values[c.date].badge}</div> : null}<div className="text-xs font-black leading-none text-slate-500">{c.day}</div><div className={`mt-2 flex min-h-6 items-center justify-center whitespace-nowrap font-black leading-none ${sizeClass(values[c.date])} ${valueClass(values[c.date])}`}>{values[c.date]?.value ?? "-"}</div></button> : <div key={`e-${i}`} className="min-h-[50px]" />)}</div></div>; }
